export const SPLASH_DELAY = 1000;

export const ORDER_FILTER_LOCATION_MODE_SEPARATOR = '.';

export const CATALOG_ORDER_KEY_TIMESTAMP = 'timestamp';
export const CATALOG_ORDER_KEY_PUBLICATION_YEAR = 'publicationYear';
export const CATALOG_ORDER_KEY_TITLE = 'title';

export const VALID_CATALOG_ORDER_KEYS = [
    CATALOG_ORDER_KEY_TIMESTAMP,
    CATALOG_ORDER_KEY_PUBLICATION_YEAR,
    CATALOG_ORDER_KEY_TITLE
];

export const ORDER_KEYS_MODEL_PATH = {};
ORDER_KEYS_MODEL_PATH[CATALOG_ORDER_KEY_TIMESTAMP] = '';
ORDER_KEYS_MODEL_PATH[CATALOG_ORDER_KEY_PUBLICATION_YEAR] = 'data.';
ORDER_KEYS_MODEL_PATH[CATALOG_ORDER_KEY_TITLE] = 'data.';

export const CATALOG_DIRECTIONS_KEY_DESC = 'desc';
export const CATALOG_DIRECTIONS_KEY_ASC = 'asc';

export const VALID_CATALOG_DIRECTIONS_KEYS = [
    CATALOG_DIRECTIONS_KEY_DESC,
    CATALOG_DIRECTIONS_KEY_ASC
];

export const DIRECTIONS_KEYS_TO_DIRECTIVE = {};
DIRECTIONS_KEYS_TO_DIRECTIVE[CATALOG_DIRECTIONS_KEY_ASC] = '+';
DIRECTIONS_KEYS_TO_DIRECTIVE[CATALOG_DIRECTIONS_KEY_DESC] = '-';

export const LOCATION_PARAM_ORDER = 'order';
export const LOCATION_PARAM_DIRECTION = 'direction';

export const CATALOG_PART_SIZE = 12;

export const LOCAL_STORAGE_PREFIX = 'kta';
export const LOCAL_STORAGE_KEY_CATALOG = 'catalog';
export const APPLICATION_CACHE_KEY_IMAGES = 'images';

export const MAX_CARD_AUTHOR_NAME_LENGTH = 20;
export const MAX_CARD_AUTHOR_SURNAME_LENGTH = 20;
export const MAX_CARD_TITLE_LENGTH = 30;
export const MIN_CARD_PAGES_COUNT = 1;
export const MAX_CARD_PAGES_COUNT = 1000;
export const MIN_CARD_AUTHORS_COUNT = 1;
export const MAX_CARD_PUBLISHER_LENGTH = 30;
export const MIN_CARD_PUBLICATION_YEAR = 1800;
export const MIN_CARD_RELEASE_DATE = new Date(
    MIN_CARD_PUBLICATION_YEAR,
    0,
    1
);